os:
  - linux-ppc64le
  - linux
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
# script: "mvn verify"

matrix:
  include:
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: linux-ppc64le
    jdk: openjdk8
